### ISSUE TITLE
R version 

### ISSUE THREAD

**Issue by jhyoon11** [fmicompbio/eisaR#21]
**When I try installing the eisaR package using the following code:** 
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install(version = 'devel')

BiocManager::install("eisaR")

**I get the following message:** 
Error: Bioconductor version '3.11' requires R version '4.0'; see https://bioconductor.org/install

Warning message:
package ‘eisaR’ is not available (for R version 3.6.3) 

Since R 4.0.0 isn't available yet, what's your suggestion for installing and running eisaR?

**Comment by csoneson** [comment]
Hi,

actually, `eisaR` is not included in Bioconductor quite yet (it's under review and we hope that it will be included shortly). The installation instructions reflect the procedure once it is included in the Bioconductor development branch. Currently, you would need to install it from the GitHub repository:

```
BiocManager::install("fmicompbio/eisaR")
```

However, that doesn't remove the dependency on R 4.0.0 (which is there since `eisaR` is developed against the development branch of Bioconductor, which uses R 4.0.0). Currently, the recommended solution would be to download and install the development version of R (which will become release 4.0.0 in a month or so), and from there install the development branch of Bioconductor, and the GitHub version of `eisaR`. 

While we don't recommend it, for the reasons outlined above, it should also be possible to install `eisaR` in R 3.6 by forking the repository or cloning it locally, removing the R version dependency and installing it from there.

**Comment by jhyoon11** [comment]
Hello, 

Thanks for the suggestion, I've installed the development version of R and tried installing eisaR from the GitHub repository. However, I get the following error:

``` 
Bioconductor` version 3.11 (BiocManager 1.30.10), R 4.0.0 alpha (2020-03-29 r78109)
Installing github package(s) 'fmicompbio/eisaR'
Downloading GitHub repo fmicompbio/eisaR@master
Installing 75 packages: GenomicRanges, GenomicFeatures, S4Vectors, IRanges, AnnotationDbi, limma, edgeR, SummarizedExperiment, BiocGenerics, rtracklayer, RCurl, GenomeInfoDbData, bitops, zlibbioc, GenomeInfoDb, XVector, Biobase, DBI, RSQLite, bit64, blob, memoise, pkgconfig, Rcpp, BH, plogr, bit, rlang, vctrs, digest, ellipsis, glue, crayon, XML, Biostrings, Rsamtools, GenomicAlignments, BiocParallel, Rhtslib, futile.logger, snow, DelayedArray, matrixStats, lambda.r, futile.options, formatR, progress, stringr, httr, openssl, BiocFileCache, rappdirs, dbplyr, dplyr, curl, jsonlite, mime, R6, askpass, hms, prettyunits, magrittr, stringi, sys, assertthat, purrr, tibble, tidyselect, cli, fansi, lifecycle, pillar, utf8, biomaRt, locfit
Error: Failed to install 'eisaR' from GitHub:
  (converted from warning) unable to access index for repository https://bioconductor.org/packages/3.11/bioc/bin/macosx/contrib/4.0:
  cannot open URL 'https://bioconductor.org/packages/3.11/bioc/bin/macosx/contrib/4.0/PACKAGES'
``` 

Is this because the package isn't included in Bioconductor yet? If so, is there another way to perform exon-intron split analysis to identify transcription/post-transcription gene regulation in RNAseq? Thanks in advance for your feedback.

**Comment by csoneson** [comment]
The most immediate issue seems to be that the warning from the `remotes` package is converted into an error (and thus if `remotes` can not find the repository it will raise an error). You can set 

```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
```

to avoid this. Then, you will have to build the packages from source since the binaries are not yet available. I just tried with the same setup (same R version, fresh installation, on a mac) and `eisaR` installs fine there.

**Comment by csoneson** [comment]
I will close this issue, but feel free to reopen if the issue persists.
