### ISSUE TITLE
Running time

### ISSUE THREAD

**Issue by cadyyuheng** [fmicompbio/eisaR#27]
Hello,

Thanks for sharing this wonderful tool! As someone who's new to genome alignment, I wonder if it is feasible to run the algorithm on my personal laptop, or I need to use high-performance clusters. Also, what's an estimated time to get the count matrices for mature and pre-mRNA? Really appreciate your help!

Thanks!

**Comment by mbstadler** [comment]
Hi @cadyyuheng 

I am happy you find it useful :-)

It should definitely be possible to run a typical analysis on a laptop with at least 4 GB (`qAlign(..., aligner = "Rbowtie")`) or 8 GB (`qAlign(..., aligner = "Rhisat2")`) of memory.

The high memory requirement is what `bowtie` or `hisat2` need during alignment for the genome index (the human genome needs about 2.5GB of memory for bowtie, and about 4.3GB for hisat2).

The main CPU requirements are for three steps:
1. index building (will take a couple of hours for a human genome, similar for bowtie or hisat2), and 2. for alignment which can make use of multiple CPU cores if available (`bowtie` aligns ~25 Mio. reads per hour and CPU, and `hisat2` should be comparable to that). Finally, getting your count table (3.) using `QuasR::qCount` is much faster than alignments and again can use multiple CPU cores if available. Using a typical RNA-seq sample with ~42 Mio. alignments and counting reads in ~0.5 Mio. exons or ~55,000 genes, qCount reached a speed of about 440 Mio. to 2000 Mio. reads per CPU hour (faster for genes than for exons because of fewer, longer regions).
In contrast to the memory, CPU will not be a hard limit as you can always wait longer and you will get what you need.

Does that answer your question?
Michael

**Comment by cadyyuheng** [comment]
Yes Michael, I'm working on the bulk-level analysis. Thanks a lot for your reply and definitely gonna try it out!
